### ISSUE TITLE
Option to offset the HUD?

### ISSUE THREAD

**Issue by SlickAmogus** [Lyall/RE5Fix#1]
First off, I love the fix, thank you for your work and for keeping this game alive. Also, sorry in advance if this isn't the right place to ask this. Is it possible to add an option to offset the HUD, so that on ultrawide resolutions it's more to the right? Or do you know of any fix/mod that does this?

**Comment by Lyall** [comment]
Do you mean having the HUD spanned? As in having the HUD be 21:9 for example instead of the default 16:9? If so I don't think there's a way to do that without incurring stretching which most people tend to dislike.

**Comment by SlickAmogus** [comment]
> Do you mean having the HUD spanned? As in having the HUD be 21:9 for example instead of the default 16:9? If so I don't think there's a way to do that without incurring stretching which most people tend to dislike.

Yes, that's what I was referring to, thank you! I don't mind either way, but I'm playing with a friend that likes having the HUD spanned.  NBD if it's not feasible.

**Comment by Lyall** [comment]
I've looked further in to this and while I think it's theoretically possible, it would probably require quite a bit of work.  As it is right now the UI is anchored to a 16:9 space. All that's easily changeable is the scale and X/Y of the entire UI canvas. To make the UI spanned would probably involve in offsetting individual parts of the UI and that gets complicated very fast, and requires significant testing. All of that to say, unfortunately it's probably not something that I'd work on. Apologies!

**Comment by SlickAmogus** [comment]
All good! Thanks for looking into it!
