### ISSUE TITLE
Latest Steam update capped at 104 Hz

### ISSUE THREAD

**Issue by Keith94** [Lyall/RE5Fix#2]
I only get 60 Hz or 104 Hz refresh rate as an option in the system settings (probably a game bug?)

Can you add an option to set a custom refresh rate ? Couldn't find another software that could fix it, yet. 

Also this guy on Steam forums got the same bug too https://steamcommunity.com/app/21690/discussions/0/3417682380504062369/

**Comment by Lyall** [comment]
It looks like the most recent update actually fixed a bunch of the issues that RE5Fix aimed to fix. It's likely that most if not all of the fix does not work at the moment. I will need to assess what still works and update accordingly. I don't have an ETA for that right now though as I'm quite busy.

As for your refresh rate bug, have you tried software like [D3Dx](https://helixmod.blogspot.com/2013/02/chiris-force-certain-resolutionhertz.html)? If that doesn't work I can look into it when I get time to reassess the latest game update, though again I'm not sure when that will be.

**Comment by Keith94** [comment]
I did indeed try D3Dx as my first choice; it normally works great for a lot of D3D9 games but it threw an error when I injected it into RE5. Also tried d3d9-wrapper by ThirteenAG and no luck.

Anyway I appreciate the response and take your time when looking into this.

**Comment by Klemci** [comment]
Using QOL fixes (yes... i need laser instead PC's horrible crosshair forced if mouse aiming) and this Reshade, i enable only yellow filter removal in .ini, looks to work without issue.

https://steamcommunity.com/sharedfiles/filedetails/?id=864823595
https://www.nexusmods.com/residentevil5goldedition/mods/110?tab=description

Thanks ;) 

EDIT: oh, and the FOV too, by the way about it, does it also speeds up player movement speed, a bit ?..

**Comment by Keith94** [comment]
can't repo anymore
